### ISSUE TITLE
[FE] Issue 상세 페이지

### ISSUE THREAD

**Issue by Kakamotobi** [issue-tracker-08/issue-tracker-max#54]
## 구현할 기능
- [x] IssueDetailPage
  - [ ] 제목 편집
  - [ ] 이슈 닫기/다시 열기
  - [ ] 이슈 삭제
  - [ ] 새 comment 작성
- [ ] Comments
  - [x] Comment 컴포넌트
  - [ ] Comment 편집 (user가 작성자라면)
- [ ] Sidebar
  - [ ] 담당자
  - [ ] 레이블
  - [ ] 마일스톤

**Comment by youzysu** [comment]
# ProgressBar
- progress tag
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress
- value: percentage max=100
