### ISSUE TITLE
[FE] 이슈 상세 페이지 Header 컴포넌트

### ISSUE THREAD

**Issue by youzysu** [issue-tracker-08/issue-tracker-max#79]
### 이슈 제목 및 상태 편집하기
- [x] 제목 편집
- [x] 열림/닫힘 편집

**Comment by Kakamotobi** [comment]
- `IssueDetailHeader`는 `issueDetails`를 `IssueDetailPage`으로부터 prop으로 받음.
- `IssueDetailHeader`에서는 이슈의 제목을 수정할 수 있어야 함.
- 기존의 제목 값을 수정 toggle 시 `TextInput`에 넣어 줌.
- 기존 방식
  - `IssueDetailHeader`에서 `useEffect`을 활용하여 `issueDetails.title`이 변경될 때 `setNewTitle(title)`로 적용.
  - 문제점
    - 처음에 stale한 값을 먼저 렌더링하고 다시 렌더를 하게된다. [Reference](https://react.dev/learn/you-might-not-need-an-effect#adjusting-some-state-when-a-prop-changes)
- 개선된 방식
  - 이전 prop 값을 상태로 두고 현재 prop과 비교해서 다르면 상태 변경.
